version: '2'
services:
  web:
    container_name: deepwater-boilerplate
    build:
      context: .
      dockerfile: DockerfileLocal
    ports:
      - '3000:3000'
      - '5858:5858'
    env_file: develop.env
    volumes:
      - .:/src:cached
