version: "2"
services:
  web:
    container_name: deepwater-boilerplate
    build:
      context: .
      dockerfile: DockerfileLocal
    ports:
      - "4000:3000"
      - "5860:5860"
    env_file: develop.env
    volumes:
      - .:/src:cached
